name: Docker CI Test
on:
  push:
    branches: [ "main" ]
jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dotnet-image -f dotnet/Dockerfile dotnet

      - name: Run container
        run: docker run --name test-container dotnet-image
