name: Docker CI Test
on:
  push:
    branches: [ "main" ]
jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t dotnet-image -f dotnet/Dockerfile dotnet

      - name: Run container
        run: docker run -d -p 5000:80 --name dotnet-container dotnet-image

      - name: Wait for container
        run: sleep 5

      - name: Test service
        run: curl http://localhost:5000
